package View;

import Model.Produto;
import DAO.ProdutoDAO;
import DAO.Conexão;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.*;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.awt.Desktop;
import java.io.*;
import java.sql.*;

public class ProdutoView extends javax.swing.JInternalFrame {

    Produto produto;
    ProdutoDAO produtoDAO;
    List<Produto> listaProduto;

    public ProdutoView() {
        produtoDAO = new ProdutoDAO();
        listaProduto = new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaProduto();
        DesativaCampos();
    }

    public void atualizarTabelaProduto() {
        produto = new Produto();
        try {
            listaProduto = produtoDAO.ListaProduto();
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String dados[][] = new String[listaProduto.size()][4];
        int i = 0;
        for (Produto produto : listaProduto) {
            dados[i][0] = String.valueOf(produto.getCodigo());
            dados[i][1] = produto.getTextoBreve();
            dados[i][2] = produto.getDescritivoCompleto();
            dados[i][3] = String.valueOf((produto.getPrecoVenda()));
            i++;
        }
        String tituloColuna[] = {"Código", "Texto Breve", "Descritivo Completo", "Saldo"};
        DefaultTableModel tabelaProduto = new DefaultTableModel();
        tabelaProduto.setDataVector(dados, tituloColuna);
        tblProduto.setModel(new DefaultTableModel(dados, tituloColuna) {
            boolean[] canEdit = new boolean[]{
                false, false, false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblProduto.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblProduto.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblProduto.getColumnModel().getColumn(2).setPreferredWidth(350);
        tblProduto.getColumnModel().getColumn(3).setPreferredWidth(70);
        tblProduto.setRowHeight(25);
        tblProduto.updateUI();
    }

    public void limpaCamposProduto() {
        txtCodigo.setText("");
        txtTextoBreve.setText("");
        txtDescritivoCompleto.setText("");
        txtPrecoAquisicao.setText("");
        txtPrecoVenda.setText("");
        txtSaldo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTextoBreve = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDescritivoCompleto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPrecoAquisicao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPrecoVenda = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnRelatorioGeral = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1024, 498));

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(768, 300));

        jLabel1.setText("Código");

        txtCodigo.setEnabled(false);

        jLabel2.setText("Texto Breve");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Informações do produto");

        jLabel16.setText("Descritivo Completo");

        jLabel17.setText("Preço Aquisição");

        jLabel18.setText("Preço Venda");

        jLabel19.setText("Saldo");

        txtSaldo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescritivoCompleto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTextoBreve, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 268, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTextoBreve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDescritivoCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtPrecoAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduto);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRelatorioGeral.setText("Relatório Geral");
        btnRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioGeralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRelatorioGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtTextoBreve.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha pelo menos o Texto Breve");
            txtTextoBreve.requestFocusInWindow();
        } else if (txtCodigo.getText().isEmpty()){
            produto = new Produto();
            produto.setTextoBreve(txtTextoBreve.getText());
            produto.setDescritivoCompleto(txtDescritivoCompleto.getText());
            produto.setPrecoAquisicao(Double.parseDouble(txtPrecoAquisicao.getText()));
            produto.setPrecoVenda(Double.parseDouble(txtPrecoVenda.getText()));
            try {
                produtoDAO.salvar(produto);
                System.out.println(produto.getTextoBreve());
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Gravado com Sucesso");
            atualizarTabelaProduto();
            PreparaSalvarCancelar();
            DesativaCampos();
            limpaCamposProduto();
        } else{
            produto = new Produto();
            produto.setTextoBreve(txtTextoBreve.getText());
            produto.setDescritivoCompleto(txtDescritivoCompleto.getText());
            produto.setPrecoAquisicao(Double.parseDouble(txtPrecoAquisicao.getText()));
            produto.setPrecoVenda(Double.parseDouble(txtPrecoVenda.getText()));
            try {
                produtoDAO.alterar(produto);

                System.out.println(produto.getTextoBreve());
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Alterado com Sucesso");
            atualizarTabelaProduto();
            PreparaSalvarCancelar();
            DesativaCampos();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um Produto");
        } else {
            produto = new Produto();
            produto.setCodigo(Integer.parseInt(txtCodigo.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja Excluir " + txtTextoBreve.getText() + "?");
            if (confirma == 0) {
                try {
                    produtoDAO.excluir(produto);
                } catch (SQLException ex) {
                    Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
                }
                atualizarTabelaProduto();
                limpaCamposProduto();
                PreparaExcluir();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCamposProduto();
        PreparaNovo();
        AtivaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
            produto = new Produto();
            produto.setTextoBreve(txtTextoBreve.getText());
            produto.setDescritivoCompleto(txtDescritivoCompleto.getText());
            produto.setPrecoAquisicao(Double.parseDouble(txtPrecoAquisicao.getText()));
            produto.setPrecoVenda(Double.parseDouble(txtPrecoVenda.getText()));
            produto.setCodigo(Integer.parseInt(txtCodigo.getText()));
            try {
                produtoDAO.alterar(produto);
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
            atualizarTabelaProduto();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        limpaCamposProduto();
        int codprod=0;
        int codigo = (Integer.parseInt(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0).toString()));
        System.out.println(codigo);
        try {
            produto = produtoDAO.BuscaProdutoporCodigo(Integer.parseInt(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 0).toString()));
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtCodigo.setText(String.valueOf(produto.getCodigo()));
        txtTextoBreve.setText(produto.getTextoBreve());
        txtDescritivoCompleto.setText(produto.getDescritivoCompleto());
        txtPrecoAquisicao.setText(String.valueOf(produto.getPrecoAquisicao()));
        txtPrecoVenda.setText(String.valueOf(produto.getPrecoVenda()));
        txtSaldo.setText(String.valueOf(produto.getSaldo()));
        PreparaSelecaoTabela();       
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposProduto();
        PreparaSalvarCancelar();
        DesativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void gerarDocumento(){
        try{
            List<Produto> lista = new ArrayList<>();
            lista = produtoDAO.ListaProduto();
            Document doc = new Document(PageSize.A4, 41.5f, 41.5f, 55.2f, 55.2f);
            PdfWriter.getInstance(doc, new FileOutputStream("C:/Relatorios/RelatorioGeralProdutos.pdf"));
            doc.open();
            
            Font f1 = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
            Font f2 = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            Font f3 = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
            Font f4 = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD);
            Font f5 = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL);
            
            Paragraph titulo1 = new Paragraph("Universidade do Estado de Minas Gerais\n\n", f2);
            titulo1.setAlignment(Element.ALIGN_CENTER);
            titulo1.setSpacingAfter(10);
            
            Paragraph titulo2 = new Paragraph("Relatorio de Produtos", f1);
            titulo1.setAlignment(Element.ALIGN_CENTER);
            titulo1.setSpacingAfter(0);
            
            PdfPTable tabela = new PdfPTable(new float[]{0,40f, 0,60f});
            tabela.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.setWidthPercentage(100f);
            
            PdfPCell cabecalho1 = new PdfPCell(new Paragraph("Descritivo do Produto",f3));
            cabecalho1.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
            cabecalho1.setBorder(0);
            
            PdfPCell cabecalho2 = new PdfPCell(new Paragraph("Saldo",f3));
            cabecalho1.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
            cabecalho1.setBorder(0);
            
            tabela.addCell(cabecalho1);
            tabela.addCell(cabecalho2);
            
            for(Produto produto:lista){
                Paragraph p1 = new Paragraph(produto.getTextoBreve(),f5);
                p1.setAlignment(Element.ALIGN_JUSTIFIED);
                PdfPCell col1= new PdfPCell(p1);
                col1.setBorder(0);
                
                Paragraph p2 = new Paragraph(Double.toString(produto.getPrecoVenda()),f5);
                p1.setAlignment(Element.ALIGN_JUSTIFIED);
                PdfPCell col2= new PdfPCell(p2);
                col2.setBorder(0);
                
                tabela.addCell(col1);
                tabela.addCell(col2);
            }
            doc.add(titulo2);
            doc.add(titulo1);
            doc.add(tabela);
            doc.close();
            
            JOptionPane.showMessageDialog(null, "Relatório salvo com sucesso");
            String caminho = "C:/Relatorios/RelatorioGeralProdutos.pdf";
            Desktop.getDesktop().open(new File(caminho));
        } catch (DocumentException e){
            e.printStackTrace();
        } catch (SQLException ex){
            ex.printStackTrace();
        } catch (IOException exx){
            exx.printStackTrace();
            JOptionPane.showMessageDialog(null, "Relatório aberto. Feche para gerar um novo!");
        }
    }
        
    private void btnRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioGeralActionPerformed
        String nomediretorio = null;
        String nomepasta = "Relatorios";
        String separador = java.io.File.separator;
        try{
            nomediretorio = "C:" + separador + nomepasta;
            if (!new File(nomediretorio).exists()){
                new File(nomediretorio).mkdir();
            }
            gerarDocumento();
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRelatorioGeralActionPerformed

    public void AtivaCampos(){
        txtTextoBreve.setEnabled(true);
        txtDescritivoCompleto.setEnabled(true);
        txtPrecoAquisicao.setEnabled(true);
        txtPrecoVenda.setEnabled(true);
    }
    
    public void DesativaCampos(){
        txtTextoBreve.setEnabled(false);
        txtDescritivoCompleto.setEnabled(false);
        txtPrecoAquisicao.setEnabled(false);
        txtPrecoVenda.setEnabled(false);        
    }
    
    public void PreparaNovo(){
        AtivaCampos();
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        tblProduto.setEnabled(false);
        tblProduto.clearSelection();
    }
    
    public void PreparaSalvarCancelar(){
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        tblProduto.setEnabled(true);
        tblProduto.clearSelection();
    }
    
    public void PreparaSelecaoTabela(){
        AtivaCampos();
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
        tblProduto.setEnabled(true);
        tblProduto.clearSelection();
    }
    
    public void PreparaAlterar(){
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        tblProduto.setEnabled(false);
        tblProduto.clearSelection();
    }
    
    public void PreparaExcluir(){
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        tblProduto.setEnabled(true);
        tblProduto.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRelatorioGeral;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescritivoCompleto;
    private javax.swing.JTextField txtPrecoAquisicao;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTextoBreve;
    // End of variables declaration//GEN-END:variables
}
